name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read        # allow checkout
  pages: write          # allow deployment to Pages
  id-token: write       # allow the Pages action to authenticate

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo code
      - uses: actions/checkout@v3

      # 2) Set up Node.js (to run your build)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build your site
      - name: Build
        run: npm run build

      # 5) Tell GitHub we’re deploying to Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 6) Upload the build output (default Vite output is in ./dist)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      # 7) Deploy to GitHub Pages
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
